"""
Common test fixtures for Python services.
Generated by Test Coverage Orchestrator
"""

from typing import Any, Dict

import pytest


@pytest.fixture
def mock_user_data() -> Dict[str, Any]:
    """Mock user data for testing."""
    return {
        "id": 1,
        "email": "test@example.com",
        "username": "testuser",
        "full_name": "Test User",
        "trust_score": 50,
        "created_at": "2026-01-13T00:00:00Z",
    }


@pytest.fixture
def mock_community_data() -> Dict[str, Any]:
    """Mock community data for testing."""
    return {
        "id": 1,
        "name": "Test Community",
        "description": "A test community for integration tests",
        "is_private": False,
        "settings": {
            "allow_public_join": True,
            "require_approval": False,
        },
    }


@pytest.fixture
def mock_mentor_profile() -> Dict[str, Any]:
    """Mock mentor profile for matching tests."""
    return {
        "user_id": 1,
        "skills": ["Python", "JavaScript", "Machine Learning"],
        "availability": ["Mon 9-5", "Wed 9-5"],
        "languages": ["English", "Spanish"],
        "experience_years": 5,
    }


@pytest.fixture
def mock_learner_profile() -> Dict[str, Any]:
    """Mock learner profile for matching tests."""
    return {
        "user_id": 2,
        "learning_goals": ["Python", "Web Development"],
        "availability": ["Mon 9-5", "Tue 9-5"],
        "languages": ["English"],
        "learning_style": "hands-on",
    }
