/**
 * Assessment test fixtures
 * Generated by Test Coverage Orchestrator
 */

export const testAssessments = {
  multipleChoice: {
    title: 'Test Multiple Choice Quiz',
    type: 'multiple_choice',
    questions: [
      {
        id: 1,
        question: 'What is 2 + 2?',
        options: ['3', '4', '5', '6'],
        correct_index: 1,
        points: 10,
      },
      {
        id: 2,
        question: 'What is the capital of France?',
        options: ['London', 'Berlin', 'Paris', 'Madrid'],
        correct_index: 2,
        points: 10,
      },
    ],
    total_points: 20,
    passing_score: 15,
  },
  essay: {
    title: 'Test Essay Assignment',
    type: 'essay',
    prompt: 'Describe your learning goals and how you plan to achieve them.',
    word_limit: 500,
    rubric: {
      clarity: 25,
      content: 50,
      structure: 25,
    },
    total_points: 100,
    passing_score: 70,
  },
  coding: {
    title: 'Test Coding Challenge',
    type: 'coding',
    prompt: 'Write a function that reverses a string.',
    language: 'javascript',
    starter_code: 'function reverseString(str) {\n  // Your code here\n}',
    test_cases: [
      { input: 'hello', expected: 'olleh' },
      { input: 'world', expected: 'dlrow' },
    ],
    total_points: 50,
    passing_score: 40,
  },
};
