/**
 * Community test fixtures
 * Generated by Test Coverage Orchestrator
 */

export const testCommunities = {
  public: {
    name: 'Test Community',
    description: 'A test community for integration tests',
    is_private: false,
    settings: {
      allow_public_join: true,
      require_approval: false,
    },
  },
  private: {
    name: 'Private Test Community',
    description: 'A private test community',
    is_private: true,
    settings: {
      allow_public_join: false,
      require_approval: true,
    },
  },
  educational: {
    name: 'Educational Test Community',
    description: 'A community focused on educational content',
    is_private: false,
    settings: {
      allow_public_join: true,
      require_approval: false,
      content_moderation: 'strict',
    },
  },
};
