/**
 * User test fixtures
 * Generated by Test Coverage Orchestrator
 */

import { hashPassword } from '../../utils/password';

export const testUsers = {
  admin: {
    email: 'admin@test.com',
    username: 'testadmin',
    password_hash: '', // Will be set in beforeEach
    full_name: 'Test Admin',
    trust_score: 100,
  },
  mentor: {
    email: 'mentor@test.com',
    username: 'testmentor',
    password_hash: '',
    full_name: 'Test Mentor',
    trust_score: 80,
  },
  learner: {
    email: 'learner@test.com',
    username: 'testlearner',
    password_hash: '',
    full_name: 'Test Learner',
    trust_score: 50,
  },
  moderator: {
    email: 'moderator@test.com',
    username: 'testmoderator',
    password_hash: '',
    full_name: 'Test Moderator',
    trust_score: 90,
  },
};

export async function hashFixturePasswords() {
  for (const user of Object.values(testUsers)) {
    user.password_hash = await hashPassword('TestPassword123!');
  }
}

export const TEST_PASSWORD = 'TestPassword123!';
