/**
 * Database helpers for integration tests
 * Generated by Test Coverage Orchestrator
 */

import { getDatabase } from '../../database';

export async function setupTestDatabase() {
  const db = getDatabase();

  // Run migrations
  await db.migrate.latest();

  return db;
}

export async function teardownTestDatabase() {
  const db = getDatabase();

  // Rollback all migrations
  await db.migrate.rollback(undefined, true);

  await db.destroy();
}

export async function truncateAllTables() {
  const db = getDatabase();

  // Get all table names except migrations
  const tables = await db('information_schema.tables')
    .select('table_name')
    .where('table_schema', 'public')
    .whereNotIn('table_name', ['knex_migrations', 'knex_migrations_lock']);

  // Disable foreign key checks
  await db.raw('SET session_replication_role = replica');

  // Truncate all tables
  for (const { table_name } of tables) {
    await db.raw(`TRUNCATE TABLE "${table_name}" RESTART IDENTITY CASCADE`);
  }

  // Re-enable foreign key checks
  await db.raw('SET session_replication_role = DEFAULT');
}

export async function cleanTestData() {
  const db = getDatabase();

  // Clean up test data (users with test emails)
  await db('users').where('email', 'like', '%@test.com').del();
  await db('communities').where('name', 'like', 'Test%').del();
}
