/**
 * Integration test setup
 * Generated by Test Coverage Orchestrator
 */

import { setupTestDatabase, teardownTestDatabase } from './database.helper';

beforeAll(async () => {
  await setupTestDatabase();
});

afterAll(async () => {
  await teardownTestDatabase();
});
